---
kind: pipeline
type: docker
name: stas-backend

clone:
  disable: true
steps:
  - name: clone
    image: harbor.jinhun.moe/library/github:latest
    commands:
      - git clone https://github.com/NJTUSTAS/STAS-MS-BackEnd .
      - git checkout ${DRONE_BRANCH}
      - ls -al
  - name: build
    image: harbor.online.njtech.edu.cn/library/golang:lumanke
    commands:
      - CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -a -o app . 
  - name: publish
    image: harbor.jinhun.moe/library/docker-drone:latest
    settings:
      tag:
        - latest
        - ${DRONE_BUILD_NUMBER}
      repo: harbor.jinhun.moe/library/stas-backend
  - name: deploy
    image: harbor.jinhun.moe/library/deploy31
    settings:
      script:
        - docker service update --with-registry-auth --image harbor.jinhun.moe/library/stas-backend:${DRONE_BUILD_NUMBER} stas_backend

